osx_image: xcode8.3

dist: trusty

sudo: false

git:
  depth: 1

language: node_js

node_js: 8

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

os:
  - linux
  - osx

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.npm/_prebuilds

notification:
  email: false

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

install:
  - npm install
  - npm install --no-save electron-builder@next

script:
  - npm test || travis_terminate 1
  - npm run build
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then electron-builder --linux --publish onTagOrDraft; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then electron-builder --mac --win --publish onTagOrDraft; fi
