environment:
  node_version: "8"

shallow_clone: true

clone_depth: 1

install:
  - ps: Install-Product node $env:node_version x64
  - set CI=true
  - npm install

test_script:
  - npm test

cache:
  - node_modules                        # local npm modules
  - '%APPDATA%\npm-cache'               # npm cache

# Don't actually build.
build: off