environment:
  node_version: "8"

shallow_clone: true

clone_depth: 1

install:
  - ps: Install-Product node $env:node_version x64
  - set CI=true
  - npm install
  - npm install electron-builder@19.19.1
  - npm run install-app-deps

test_script:
  - npm test

cache:
  - node_modules                        # local npm modules
  - '%APPDATA%\npm-cache'               # npm cache

# Don't actually build.
build: off